### ISSUE TITLE
Python 2.6 support

### ISSUE THREAD

**Issue by jayvdb** [Lukasa/hyper#130]
There is at least one syntax problem with Python 2.6

https://travis-ci.org/jayvdb/anyhttp/jobs/60482491#L1712

I havent investigated further, but would be happy to dig around a little and put up a comprehensive patch if there is interest in supporting Python 2.6.
(if not, feel free to close this issue as wontfix ;-))

**Comment by Lukasa** [comment]
@jayvdb I'm interested to know why Python 2.6 support is something you feel you should provide. I'm generally in agreement with Alex Gaynor that [Python 2.6 should be abandoned](https://alexgaynor.net/2015/mar/30/red-hat-open-source-community/) because it's been unsupported for more than 18 months now.

As a result, my default position is that supporting Python 2.6 is out of scope. However, if you've got a compelling reason to offer that support, and the delta required to obtain that support in hyper is not large, then I'm open to adding best-effort 2.6 support.

**Comment by jayvdb** [comment]
Hasten the day that py2.6 is abandoned, and I offer no reason for hyper to support it.  I only raised this issue as I didnt see any issue about this topic, and it is better to have a affirmative decision about minimum platform being supported.  http://hyper.readthedocs.org/en/latest/ says only "Python 3.4 and Python 2.7.9", yet I see 3.3(.5) tests all pass on https://travis-ci.org/Lukasa/hyper .

fwiw, my package needs to support py2.6 as an application on top of it needs to maintain py2.6 support.
However my package can skip hyper if used in a py2.6 environment, and select one of the many other http clients which does support py2.6.

**Comment by Lukasa** [comment]
> http://hyper.readthedocs.org/en/latest/ says only "Python 3.4 and Python 2.7.9", yet I see 3.3(.5) tests all pass on https://travis-ci.org/Lukasa/hyper .

Yeah, that's some weasel-wording. Python 3.3 was supportable, but PyOpenSSL didn't do what we needed it to do. That's changed, so I can now claim that Python 3.3 does work, and will likely update the docs to mention it.

Generally, I'm inclined not to add 2.6 support at this time. However, should anyone else come along with a compelling reason to support 2.6 then I'm open to the discussion.

@jayvdb Thanks for the feedback, let me know how using hyper goes for you!
