### ISSUE TITLE
Missing window updates after INITIAL_WINDOW_SIZE update? 

### ISSUE THREAD

**Issue by sevajide** [Lukasa/hyper#190]
#185 breaks some tests of mine.  I'm testing using a server that updates the initial window size via the settings value SettingsFrame.INITIAL_WINDOW_SIZE.  After #185, it freezes while reading a response greater than 64k, the original value of INITIAL_WINDOW_SIZE.

This suggests that the server is expecting a WINDOW_UPDATE that does not get sent.
Reverting 190e89462ae810cbcaabb87eb305ae2c6b4a163c corrects this.

I.e, 190e89462ae810cbcaabb87eb305ae2c6b4a163c is correct - the stream should be created with the updated initial window size; but it seems to have uncovered a bug in the interaction between the stream and/or connection and the window manager

**Comment by Lukasa** [comment]
Hmm, that seems likely to me. Let me take a quick look and see what I can see.

**Comment by Lukasa** [comment]
Oh, hang on, that diagnosis isn't quite right. I think this is going the other way around.

So, to be clear, if the *server* sends SETTINGS_INITIAL_WINDOW_SIZE, that means the server is restricting the amount of data the *client* can send. The change that we're looking at affects the amount of data the *server* can send.

However, I think the end result is the same.

The big problem, AFAICT, is that we fixed this bug wrongly. The magic number there was *right*, because hyper does not restrict the initial window size. The thing that is wrong is the line a few lines below the original change, where we set the outbound flow control window equal to the *connection*'s outbound flow control window.

Let's fix that up.

**Comment by Lukasa** [comment]
Do you want to try applying the diff from #191 and see if that resolves your problem or introduces new ones?

**Comment by sevajide** [comment]
The patch from #191 works! So far, there are no new issues. Thank you for addressing this so quickly.

**Comment by Lukasa** [comment]
No problem. I'll see if I can think of a specific test to add for this regression and then merge #191.
