### ISSUE TITLE
Download stream server connection example?

### ISSUE THREAD

**Issue by lithiumlab** [Lukasa/hyper#278]
Is there a minimal example available to test server pushes like http2bin.org?
If not, what would be your recommendation on creating a test scenario?

Before testing against an external API i want to make sure there's no obvious errors in the python layer. A minimal test should be a good starting point.

**Comment by Lukasa** [comment]
There is not. =) http2bin.org does not currently support it because it's a WSGI application and there is no standard for how they can trigger pushes. In this case, however, it in principle *could*, but it's finicky and difficult.

My recommendation, if you want to test this code, is to write a version of one of the hyper-h2 example servers [here](https://github.com/python-hyper/hyper-h2/tree/master/examples) that pushes a response.

**Comment by lithiumlab** [comment]
Excellent, thanks for clarifying.

**Comment by lithiumlab** [comment]
Hi again, Cory;

I'm using hyper to connect to AVS (Alexa Voice Service) API.
I have successfully connected and received data from a POST request using hyper.

One requisite to maintain a downchannel to get cloud initiated directives from the AVS  is to make a GET request to `/directives`

When doing a .read() on that HTT20Response Object i get the following error:
`SSLError: ('The read operation timed out',)`

Is there a kind of **timeout** setting we can tweak to be able to receive information in the download stream?

I'm currently using Flask, requests, HTTP20Adapter in Python 2.7.11

**Here a bit of information collected from AVS forums answers:**

> When you make a GET request to /directives you will get a 200 Status Code, but not necessarily any content in the response body. It will not close the response stream until you manually close it, or the service closes the connection (which happens on an hourly basis). You need to make sure that you have your READ timeout set to 0 in curl so that if you don't receive data on the downchannel GET request (which you might not) that it doesn't timeout. You're basically long-polling /directives waiting for something to come down on it.

**Here another bit of information collected from AVS forums:**

> You should not be constantly creating and closing a down channel stream. The point of the down channel is to have an always open connection between your device and Alexa so that it can send directives "in the background", potentially not initiated by user speech. For instance, setting volume via the companion app. You should create the down channel once, when you start your device. That stream should remain open indefinitely (don't have any timeouts on it). If the connection ever gets closed, you should reopen it. You should not use the down channel to send anything to AVS. Does that answer your question?


**This is from the AVS docs:**

To establish a downchannel stream your client must make a GET request to /directives within 10 seconds of opening the connection with AVS. The request should look like this:
```
:method = GET
:scheme = https
:path = /{{API version}}/directives
authorization = Bearer {{YOUR_ACCESS_TOKEN}}
```
Following a successful request, the downchannel stream will remain open in a half-closed state from the client and open from AVS for the life of the connection. It is not uncommon for there to be long pauses between cloud-initiated directives.
[AVS Docs](https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/managing-an-http-2-connection)

**Comment by lithiumlab** [comment]
Here's the call:

		s = requests.Session()
		s.mount(http2_conn_url, h2adapter )

		headers = {
			'authorization' : 'Bearer ' + str(token),
		}
		first = s.get( http2_conn_url + '/v20160207/directives', headers=headers, stream=True)
		print('________________')
		print(first.headers)
		print(first.status_code)
		stream_id = first.raw._stream.stream_id
		print(stream_id)
		first.raw.read()
		print('________________')
		return str(first.raw.status)

**Comment by Lukasa** [comment]
Hi there!

This is an awkward side-case for hyper, because AWS are doing something that hyper really doesn't expect. Specifically, if you call `read()` on the `HTTP20Response`, it will attempt to read until END_STREAM. Given that you're not expecting END_STREAM to *ever* show up, that will necessarily mean that it will continue to attempt to read from the socket until, eventually, the socket times out and this error is thrown.

Now, that's ok: you can choose to ignore the error. But ultimately, you might need to consider whether this is not the best approach. This is ultimately an asynchronous programming concern. You either need to run this in a background thread so you can block on the read (and either set no timeout or allow these timeouts), or you need to consider moving to an async framework. However, there is no sensible API that I can provide that will behave in a way that works nicely with this AWS API that doesn't rely on either of those.

**Comment by lithiumlab** [comment]
Thanks for this helpful information.
By "block on the read" you meant "lock on the read" right?

**Comment by Lukasa** [comment]
Nope, I mean block. =)
