### ISSUE TITLE
http20 response and stream have no way of reading 0-or-more bytes in a non blocking manner 

### ISSUE THREAD

**Issue by james-huang** [Lukasa/hyper#282]
Really appreciate the work put in on hyper @Lukasa. First of I would like to say I'm trying to write an Alexa integration in python and I dont know what I'm doing. Alexa wants http2, and hyper is the only http2 python library out there. 

Alexa Integrations have 2 way communication on the **same connection**. There is a downchannel stream that Alexa will occasionally push directives to that we need to poll for. This is what an interaction might look like:

```
Downchannel Stream req: set up downchannel stream

Client Req Stream1: What is the audio? ("Alexa, set a 20 second timer")
Alexa Resp Stream1: Play this mp3 ('setting timer for 20 seconds')

Client Req Stream2: Playing mp3
Client Req Stream3: Mp3 finished

Downchannel Stream resp: Set a 20 second timer
```

So I think I have to poll on the downchannel stream somehow. Doing a single read() on the stream response causes Stream._read() to block on the while loop, as the connection is never closed. It seems like this also prevents me from uploading audio for recognition purposes. I am assuming its because of the _read_lock on the HTTP20Connection. Not quite sure. 

Stream._read(amt) has this nice feature of returning amt-or-more bytes of data if its availible. However, it does not currently work for amt=0
So for my purposes I've added this in front of the while loop in the read function.

```
if not self.remote_closed:
    self._recv_cb(stream_id=self.stream_id)
```

HTTP20Response.read(amt) does not do the returning 0-or-more bytes of data. For my purposes I've added that functionality when 0 is passed into amt.

```
if amt == 0:
    # if amt is 0, return all data we got
    self._data_buffer += self._stream._read(0)
    data = self._data_buffer
    self._data_buffer = b''
    response_complete = True
```

This seems to solve my blocking issue, as now I can happily call resp.read(amt=0) on the downchannel stream response. And resp.read(amt=0) seems to work on the non-downchannel stream responses that I know for a fact contains data. So that is good. Does it make any sense to mainline any of these changes? 

[0] https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/reference/timers-and-alarms-conceptual-overview#scenario1
[1] https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/docs/managing-an-http-2-connection
[2] https://forums.developer.amazon.com/questions/38907/establishing-an-alexa-voice-downchannel-stream-in.html
[3] https://forums.developer.amazon.com/questions/38986/alexa-set-timer-request-responds-with-audio-error.html

**Comment by Lukasa** [comment]
Thanks for this investigative work! This is a really good start. =D

So the discussion here turns on how we expect the HTTP/2 connection to behave. Right now when an attempt is made to read data for a response, a number of internal buffers are processed which may be able to satisfy the read. If they can't, we then call `recv_into` on the socket. Specifically, `_recv_cb` is configured in such a way that if there is no data for the response in question then it will *always* call `recv_into`. If there's no data for a response *and* no data on the socket, then I'd expect your `read(0)` call to block until data is received from the remote peer.

There is no easy way, currently, to signal to the connection that you'd like to read *if the socket is readable*, and otherwise to do nothing. It is *possible* to achieve this by passing a flag around, but ultimately this leads to a pretty nasty interaction design whereby you end up polling the downstream stream for more data. That repeated polling is a bit silly: ideally you'd want to be called back when there is data received on that stream.

Ultimately, however, the hyper library is ill-suited to this use-case. Its interaction model (the fact that it is called by the user) leaves us in a place where we cannot enormously effectively handle the kind of asynchronous programming model you're working with here. Fundamentally it expects responses, rather than ongoing data streams that never end. =P

I'm totally happy that you've found a workaround that works for you, but I ultimately think that the best solution here comes in the form of rethinking the way the hyper library works at a pretty profound level.

**Comment by ilbarone92** [comment]
Hello I think I'm experimenting the same problem when trying to establishing an Alexa AVS downchannel http2.
The problem is that when I have to read asynchronous data coming down on downchannel the response.READ call is blocking the channel, even of opening another thread.
Can u confirm me that this reading 0 byte method solved the Issue and made u able to read asynchronous data? 
Thanks for caring,

Alessio
