### ISSUE TITLE
HTTPS proxy support

### ISSUE THREAD

**Issue by chripede** [Lukasa/hyper#304]
Is this planned? I see that proxy support for http is included, but since almost every host only serves HTTP2 on https it seems kind of useless.

**Comment by Lukasa** [comment]
"planned" is a tricky term.

This project is not hugely actively developed at the moment, primarily because my main focus right now is on rewriting urllib3 with an eye towards a HTTP/2 future. This means that I don't have any time to actively develop code for this library. However, I'm happy to code-review patches, including a patch that would add this functionality, so if you or someone else would like to take up the work to do it then I'm happy to work with them.

**Comment by vfaronov** [comment]
@Lukasa 

> my main focus right now is on rewriting urllib3 with an eye towards a HTTP/2 future

Does this mean that Hyper will essentially be obsoleted by urllib3 2.0?

**Comment by Lukasa** [comment]
@vfaronov The answer is "it depends". Eventually, I'd like it to be, yes. But we're a very long way around from that.

Hyper still has an active and valuable role to play in the Python HTTP ecosystem, and I certainly won't prevent people from maintaining and improving Hyper in the long term. Indeed, I'm looking at adding some co-maintainers in future because I don't have a bunch of time to spend on Hyper at the moment.

Certainly, urllib3 v2 will not contain HTTP/2 support: only the hooks necessary for adding it. In the long term we may add it in a future patch, but that's definitely at least 6 months away.

**Comment by LLCampos** [comment]
My understanding is that this issue was solved by #322. Better to close it to avoid confusion?

**Comment by Lukasa** [comment]
Yup. 😁
